version: '3'
services:
  web:
    image: karkkn96/exercises:tag_of_this_image
    build: .
    command: bash -c "python -m worker.warming && /usr/local/bin/supervisord -c ./gunicorn/supervisord.conf"
    ports:
     - "8020:8020"
    depends_on:
      - worker
    environment:
      - DEPLOY_ENV=COMPOSE
  worker:
    image: karkkn96/exercises:tag_of_this_image_2
    build: .
    command: bash -c "python -m worker.warming && /usr/local/bin/supervisord -c ./worker/supervisord.conf"
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - DEPLOY_ENV=COMPOSE
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
     - "5672:5672"
     - "15672:15672"
