version: '3'
services:
  web:
    build: .
    command: bash -c "python -m worker.warming && /usr/local/bin/supervisord -c ./gunicorn/supervisord.conf"
    networks:
      - demo
    ports:
     - "8020:8020"
    depends_on:
      - worker
    environment:
      - DEPLOY_ENV=COMPOSE
  worker:
    build: .
    command: bash -c "python -m worker.warming && /usr/local/bin/supervisord -c ./worker/supervisord.conf"
    networks:
      - demo
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - DEPLOY_ENV=COMPOSE
  redis:
    image: "redis"
    networks:
      - demo
    ports:
      - "6379:6379"
  rabbitmq:
    image: "rabbitmq:3-management"
    networks:
      - demo
    ports:
     - "5672:5672"
     - "15672:15672"

networks:
  demo:
    # Use a custom driver
    external:
      name: demo
